#
# Crowdin configuration file
# https://support.crowdin.com/configuration-file/
#

# Your Crowdin project ID
"project_id": "810696"

# API token for authentication (keep this secret!)
"api_token_env": "CROWDIN_TOKEN" # Will read from environment variable

# Base path for local files
"base_path": "."

# Files to translate
files:
  # Addon configuration translations
  - source: "/translations/en.json"
    translation: "/translations/%two_letters_code%.json"

  # UI strings (to be created later)
  - source: "/translations/ui/en.json"
    translation: "/translations/ui/%two_letters_code%.json"

# Settings
preserve_hierarchy: true
commit_message: "chore: Update translations from Crowdin"
append_commit_message: false
