[tool.black]
line-length = 120
target-version = ['py312', 'py313']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | venv-.*
  | _build
  | buck-out
  | build
  | dist
  | legacy
)/
'''

[tool.isort]
profile = "black"
line_length = 120
skip_glob = ["venv*", "legacy/*"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 120
exclude = "venv*,legacy,.git,__pycache__,build,dist"
ignore = "C901,E501"
# E203 is incompatible with black, but we want to catch it for slices
# Black should handle this correctly with proper configuration