analyze_entities:
  name: Analyze Entities
  description: Analyze entities and preview renaming without making changes
  fields:
    limit:
      name: Limit
      description: Maximum number of entities to analyze
      required: false
      default: 10
      selector:
        number:
          min: 1
          max: 1000
    skip_reviewed:
      name: Skip Reviewed
      description: Skip entities with 'maintained' label
      required: false
      default: false
      selector:
        boolean:
    show_reviewed:
      name: Show Only Reviewed
      description: Show only entities with 'maintained' label
      required: false
      default: false
      selector:
        boolean:

rename_entity:
  name: Rename Entity
  description: Rename a single entity according to naming convention
  fields:
    entity_id:
      name: Entity
      description: The entity to rename
      required: true
      selector:
        entity:

rename_bulk:
  name: Bulk Rename Entities
  description: Rename multiple entities according to naming convention
  fields:
    entity_ids:
      name: Entities
      description: List of entities to rename
      required: false
      selector:
        entity:
          multiple: true
    limit:
      name: Limit
      description: Maximum number of entities to rename (if entity_ids not provided)
      required: false
      default: 10
      selector:
        number:
          min: 1
          max: 100
    skip_reviewed:
      name: Skip Reviewed
      description: Skip entities with 'maintained' label
      required: false
      default: true
      selector:
        boolean:
    dry_run:
      name: Dry Run
      description: Preview changes without applying them
      required: false
      default: true
      selector:
        boolean: