name: Crowdin Action

on:
  push:
    branches: [main, next-release]
    paths:
      - "translations/**/*.json"
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin action
        uses: crowdin/github-action@v1
        with:
          # Upload sources to Crowdin
          upload_sources: true
          # Upload translations to Crowdin, only use true at initial run
          upload_translations: true
          # Automatically approves uploaded translations
          auto_approve_imported: false
          # Download translations from Crowdin
          download_translations: true
          # Path to your Crowdin configuration file
          config: "crowdin.yml"
          # Create pull request with translations
          create_pull_request: true
          pull_request_title: "New Crowdin translations"
          pull_request_body: "New translations from Crowdin"
          pull_request_labels: "translations, crowdin"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
